"""
get_upstox_token.py
Daily login helper for Upstox API access tokens.

Upstox access tokens expire every day (same as Zerodha Kite), so this needs
to be run once each morning before the dashboard uses live data.

Usage:
    python scripts/get_upstox_token.py

It will:
  1. Ask for your API Key + Secret (or read from .env if already saved)
  2. Open the Upstox login page in your browser
  3. After you log in, Upstox redirects to https://localhost/?code=XXXX
     (the page itself will show "can't reach this page" — that's expected,
     we don't run a real server there. Just copy the FULL URL from the
     browser's address bar and paste it back here.)
  4. Exchange that code for an access_token
  5. Save everything to a .env file so app.py can read it automatically
"""

import os
import re
import webbrowser
from urllib.parse import urlencode, urlparse, parse_qs

import requests

ENV_FILE = os.path.join(os.path.dirname(__file__), "..", ".env")


def load_existing_env():
    values = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    values[k.strip()] = v.strip().strip('"')
    return values


def save_env(values: dict):
    with open(ENV_FILE, "w") as f:
        f.write("# Auto-generated by get_upstox_token.py\n")
        f.write("DATA_SOURCE=upstox\n")
        for k, v in values.items():
            f.write(f'{k}="{v}"\n')
    print(f"\n✅ Saved to {os.path.abspath(ENV_FILE)}")


def main():
    existing = load_existing_env()

    api_key = existing.get("UPSTOX_API_KEY") or input("Upstox API Key (client_id): ").strip()
    api_secret = existing.get("UPSTOX_API_SECRET") or input("Upstox API Secret (client_secret): ").strip()
    redirect_uri = existing.get("UPSTOX_REDIRECT_URI") or "https://localhost"

    # Step 1: Build the login/authorization URL
    auth_params = {
        "client_id": api_key,
        "redirect_uri": redirect_uri,
        "response_type": "code",
    }
    auth_url = f"https://api.upstox.com/v2/login/authorization/dialog?{urlencode(auth_params)}"

    print("\nOpening Upstox login in your browser...")
    print("If it doesn't open automatically, visit this URL manually:\n")
    print(auth_url)
    webbrowser.open(auth_url)

    print(
        "\nAfter logging in, the browser will try to redirect to "
        f"'{redirect_uri}' and likely show a 'site can't be reached' error "
        "-- that is expected, ignore it."
    )
    print("Just COPY THE FULL URL from the address bar (it contains ?code=...) "
          "and paste it below.\n")

    pasted = input("Paste the redirected URL here: ").strip()

    # Extract the auth code, whether they pasted the full URL or just the code
    code = None
    if pasted.startswith("http"):
        parsed = urlparse(pasted)
        code = parse_qs(parsed.query).get("code", [None])[0]
    else:
        # maybe they just pasted the code itself
        match = re.match(r"^[A-Za-z0-9\-_]+$", pasted)
        if match:
            code = pasted

    if not code:
        print("\n❌ Could not find an authorization code in what you pasted. "
              "Make sure you copied the full URL after login, including '?code=...'.")
        return

    print(f"\nGot authorization code: {code[:8]}...")

    # Step 2: Exchange the code for an access token
    token_url = "https://api.upstox.com/v2/login/authorization/token"
    payload = {
        "code": code,
        "client_id": api_key,
        "client_secret": api_secret,
        "redirect_uri": redirect_uri,
        "grant_type": "authorization_code",
    }
    headers = {"accept": "application/json", "Content-Type": "application/x-www-form-urlencoded"}

    resp = requests.post(token_url, data=payload, headers=headers, timeout=15)

    if resp.status_code != 200:
        print(f"\n❌ Token exchange failed ({resp.status_code}): {resp.text}")
        return

    data = resp.json()
    access_token = data.get("access_token")

    if not access_token:
        print(f"\n❌ No access_token in response: {data}")
        return

    print(f"\n✅ Access token received: {access_token[:12]}...")

    save_env({
        "UPSTOX_API_KEY": api_key,
        "UPSTOX_API_SECRET": api_secret,
        "UPSTOX_REDIRECT_URI": redirect_uri,
        "UPSTOX_ACCESS_TOKEN": access_token,
    })

    print("\nNow run the dashboard with:")
    print("  python -m streamlit run app.py")
    print("(app.py will auto-load DATA_SOURCE and the token from .env)\n")


if __name__ == "__main__":
    main()
